apiVersion: v1
clusters:
- cluster:
    certificate-authority-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUR4akNDQXE2Z0F3SUJBZ0lVWU5RcURBeXM0cmdaTk8zaU8wTG1RK3UyM25Zd0RRWUpLb1pJaHZjTkFRRUwKQlFBd2FERUxNQWtHQTFVRUJoTUNRMDR4RURBT0JnTlZCQWdUQjBKbGFVcHBibWN4RURBT0JnTlZCQWNUQjBKbAphVXBwYm1jeEREQUtCZ05WQkFvVEEyczRjekVTTUJBR0ExVUVDeE1KTkZCaGNtRmthV2R0TVJNd0VRWURWUVFECkV3cHJkV0psY201bGRHVnpNQ0FYRFRFNU1USXhOakE1TXpjd01Gb1lEekl4TVRreE1USXlNRGt6TnpBd1dqQm8KTVFzd0NRWURWUVFHRXdKRFRqRVFNQTRHQTFVRUNCTUhRbVZwU21sdVp6RVFNQTRHQTFVRUJ4TUhRbVZwU21sdQpaekVNTUFvR0ExVUVDaE1EYXpoek1SSXdFQVlEVlFRTEV3azBVR0Z5WVdScFoyMHhFekFSQmdOVkJBTVRDbXQxClltVnlibVYwWlhNd2dnRWlNQTBHQ1NxR1NJYjNEUUVCQVFVQUE0SUJEd0F3Z2dFS0FvSUJBUUR1UFdzMFhVTmYKQXRRWWhZd2JrVE9xRVdzTmlvUUlCeG5NZEoxWWNScUxXWmVtWERZQy9NVXhNOWJVWllVa3ZzY2FSU1RNbkpPdApsamMzZWVTcFlydmVkLytzdEZSOHdncnhialBCMENDSjdmN2U0TllsRVFodHYrbXRaRHJDaHRDeFF0WDVENCswCm43cUhFcU9OT3k4eXA1RUZROU94QnA4WmJvbithQTdQZW12Vit3YmZGalFuV3lLWU9ENlhrdlE5OFBQejk5SjkKODRzcUwwODA1VkkyU01Sa0wzNCttbUhZU1kzM3Jnc1BiTjd4MXlZU0hoWmEzNzFlaXB5WnI0TEgrNmNtelk0KwpodGZFYVpFemdoczhxSXlqTU91WjAxS29XVXBTVit2TGxCbTc3ZTU5dlJkeXBXZy9ZT0dHNUVIS0xrTk91MTE1Ck9kWW1ENldtOGxabkFnTUJBQUdqWmpCa01BNEdBMVVkRHdFQi93UUVBd0lCQmpBU0JnTlZIUk1CQWY4RUNEQUcKQVFIL0FnRUNNQjBHQTFVZERnUVdCQlNGTzJnV0hRR1F3Z3M4NklLV2dLcjhZVVRnV3pBZkJnTlZIU01FR0RBVwpnQlNGTzJnV0hRR1F3Z3M4NklLV2dLcjhZVVRnV3pBTkJna3Foa2lHOXcwQkFRc0ZBQU9DQVFFQUFjM2lBVzdTCjdSVXJpSXV1bEV0SGJBU2xTdmVndTdXallBNUZnQWJic0FNRml6bU9SMm56SGRJSnYrMFo5ZmlWMlFCZ1M3eVMKYm9qOFREcVB3bEJtY25tTzVOU2owSEtJOXdmYWs1TURNYWZCeWdDTG1KVDhWZElXZkRBK2xrUmlBRnczVTFOYQpEVGZxbXBSU2MzTGoxcnVxOFVnaUJWZUZoMEFvem5yNTl4b2M2TXBQd2NHZ1BvOTVkOFB0ZHMwMWFOUXpXRzh0CkhMZGxsL25xYkJNRVJYbmtQR094SVkrTFBUcnNicVllbEhnQXJEcEg3ZktRbm1MVTBGVFByRDFja1BKTld3SUYKS3JBaXk0Mnd1K2dYS3ZQOGRPRjNHZE4rVG9GSXBhRkdRWGJKWnBobWdpZDYrVFFaSXJzK0tnSHQvVUpqelNTTwpoTE8raU52bjcybWVyZz09Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
    server: https://127.0.0.1:8443
  name: default-cluster
contexts:
- context:
    cluster: default-cluster
    namespace: default
    user: default-auth
  name: default-context
current-context: default-context
kind: Config
preferences: {}
users:
- name: default-auth
  user:
    client-certificate: /etc/kubernetes/cert/kubelet-client-current.pem
    client-key: /etc/kubernetes/cert/kubelet-client-current.pem
